--- 
:log_level: 1
:save_rate: 1440
:debug: false
:admin: supercool
:goid_type: ":guid"
:port: 8888
:update_rate: 30
:restart_delay: 10
:address: 0.0.0.0
:intro_file: intro.txt
:start_room: 2ed14ca1-4ab1-0a21-9f0f-608d8d847431
:restart_limit: 15
:mccp: false
:mssp: false
